### ISSUE TITLE
Tegn i tekst som danner grunnlag for søk på næringskoden

### ISSUE THREAD

**Issue by SolrunHoem** [offentlig-ai/nace-predictor#1]
Når det brukes tegn i teksten som skal danne grunnlag for søk på næringskoden, gir ikke tjenesten alltid resultatet som vi forventer for treff på næringskoder. Eksempel på tegn i teksten kan være komma, skråstrek, punktum, bindestrek.
Det ser heller ikke ut til å fungere med store bokstaver i REST-tjenesten. Vi har tatt hensyn til dette under utviklingen internt i vårt saksbehandlingssystem, men det beste hadde vært om dette hadde ligget hos dere/kilden.

**Comment by stigbd** [comment]
Viss dette issuet ikkje er løyst, bør det antagelegvis opprettast på nytt her:
https://github.com/datautvikling/nace-predictor
